name: 'WPLatest'
description: 'This action makes it easy to interact with the WPLatest API.'
author: 'Chris Jayden'

branding:
  icon: 'rocket'
  color: 'red'

inputs:
  'wplatest-token':
    description: 'WPLatest API token'
    required: true
  'wplatest-action':
    description: 'WPLatest action'
    required: true
  'wplatest-template-slug':
    description: 'WPLatest template slug'
    required: true
  'github-token':
    description: 'GitHub token'
    required: true
  'wplatest-artifact-zip-url':
    description: 'Url to the zip file'
    required: false
  'repo-id':
    description: 'GitHub repository ID'
    required: true
  'timeout-seconds':
    description: 'Timeout in seconds'
    required: false
  'update-comment':
    description: 'Whether or not to update any comments or to create a new one'
    required: false

outputs:
  wplatest_url:
    description: 'WPLatest WordPress URL'
  wplatest_magic_login_url:
    description: 'WPLatest Magic Login URL'

runs:
  using: 'node20'
  main: 'dist/index.js'
