name: 'WPLatest'
description: 'This action makes it easy to interact with the WPLatest API.'
author: 'Chris Jayden'

branding:
  icon: 'rocket'
  color: 'red'

inputs:
  'wplatest-secret':
    description: 'WPLatest API token'
    required: false
  'wplatest-action':
    description: 'WPLatest action'
    required: true
  'wplatest-plugin-id':
    description: 'WPLatest plugin id'
    required: true
  'github-token':
    description: 'GitHub token'
    required: true
  'wplatest-artifact-zip-url':
    description: 'Url to the zip file'
    required: true

outputs:
  version:
    description: 'WPLatest new plugin version'
  id:
    description: 'WPLatest new plugin version id'

runs:
  using: 'node20'
  main: 'dist/index.js'
